apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp
  labels:
    app: chatapp
spec:
  template:
    metadata:
      labels:
        app: chatapp
    spec:
      containers:
      - name: chatapp
        image: vootlasaicharan/chatroom-application:9
        ports:
        - containerPort: 8080
  replicas: 1
  selector:
    matchLabels:
      app: chatapp
